---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
  name: gitea-operator
  namespace: gitea-operator
spec:
  targetNamespaces: []
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
  name: gitea-operator
  namespace: gitea-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gitea-operator
  source: redhat-rhpds-gitea
  sourceNamespace: gitea-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
  name: redhat-rhpds-gitea
  namespace: gitea-operator
spec:
  sourceType: grpc
  image: quay.io/rhpds/gitea-catalog:latest
  displayName: Red Hat Demo Platform (Gitea)
  publisher: Red Hat Demo Platform
---