apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "1"
  name: cloud-beaver
  namespace: cp4ba-common
  labels:
    app: cloud-beaver
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: cloud-beaver
  replicas: 1
  template:
    metadata:
      annotations:
        openshift.io/required-scc: "privileged"
      labels:
        app: cloud-beaver
    spec:
      containers:
        - name: cloud-beaver
          image: dbeaver/cloudbeaver:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8978
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
      serviceAccount: cp4ba-common-sa
      serviceAccountName: cp4ba-common-sa

