apiVersion: v1
kind: Service
metadata:
  name: cloud-beaver
  namespace: cp4ba-common
  labels:
    app: cloud-beaver
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9080
    targetPort: 8978
  selector:
    app: cloud-beaver
